version: "3.8"

services:
  lecture-database:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=lecture"
    ports:
      - "5440:5432"